version: 2
jobs:
  build-python27:
    docker:
      - image: python:2.7-alpine3.8
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            apk add --no-cache make bash
            pip install . pytest pytest-cov flask
      - run:
          name: run tests
          command: make _tests

  build-python36:
    docker:
      - image: python:3.6-alpine3.8
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            apk add --no-cache make bash
            pip install . pytest pytest-cov flask
      - run:
          name: run tests
          command: make _tests

workflows:
  version: 2
  build:
    jobs:
      - build-python27
      - build-python36
