# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build-python27:
    docker:
      - image: python:2.7
    working_directory: ~/sippycup
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install virtualenv
            virtualenv venv
            . venv/bin/activate
            pip install . pytest pytest-cov flask
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            py.test --cov-report term-missing --cov=sippycup tests/
      - store_artifacts:
          path: test-reports
          destination: test-reports

  build-python36:
    docker:
      - image: python:3.6
    working_directory: ~/sippycup
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install . pytest pytest-cov flask
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            py.test --cov-report term-missing --cov=sippycup tests/
      - store_artifacts:
          path: test-reports
          destination: test-reports

workflows:
  version: 2
  build:
    jobs:
      - build-python27
      - build-python36
